SINTEF/dlite

examples/read-csv/python-storage-plugins/csv.py, examples/read-csv/readcsv.py, storages/python/python-storage-plugins/csv.py
Changes the syntax of pandas_opts to a comma-separated list of `"key":value` pairs. `value` may be any basic python expression.
=> Allow type-conversion in pandas_opts options to the csv storage

CMakeLists.txt, storages/hdf5/CMakeLists.txt, storages/json/CMakeLists.txt, storages/python/CMakeLists.txt, storages/rdf/CMakeLists.txt
Should we also statically link dlite-utils into dlite? That would produce a single DLite library (both shared and static).
I guess it is preferable to not link Python and NumPy statically to allow to use dlite with different (binary compatible) versions of Python and NumPy.
=> Statically linked dlite and dlite-utils into the plugins

src/utils/plugin.c
Added workaround for issue #154 to ensure that the test_storage test does not segfaults.
Add a new issue for fix the actual problem with FreeLibrary
Note, this fix build on top of branch fix_issue151 (from PR #152).
=> Issue154 fix test storage

CMakeLists.txt, bindings/python/CMakeLists.txt
Added two workarounds
* Copy all DLLs to the dlite Python package in binary dir, such
that they can be found by the Python tests.
* Strip off initial "Z:" from paths when cross-compiling with MinGW.
=> Fix failing tests when cross-compiling with MinGW

bindings/python/dlite-entity.i, bindings/python/tests/CMakeLists.txt, bindings/python/tests/global_dlite_state_mod1.py, bindings/python/tests/global_dlite_state_mod2.py, bindings/python/tests/global_dlite_state_mod3.py, bindings/python/tests/global_dlite_state_mod4.py, bindings/python/tests/global_dlite_state_sub.py, bindings/python/tests/test_entity.py, bindings/python/tests/test_global_dlite_state.py, bindings/python/tests/test_python_bindings.py, src/dlite-entity.c, src/dlite-entity.h, storages/json/tests/test_json_storage.c
Adds a function to dlite-entity.c and the respective Python bindings to inspect the internal storage of dlite. Adds a Python-test.
Example from Python
```
import dlite
print(dlite.istore_get_uuids())
```
Returns a list of uuids available in the internal storage. Primarily intended for debugging/testing.
=> Python bindings to inspect dlites internal storage

bindings/python/dlite-entity-python.i, bindings/python/dlite-python.i, bindings/python/tests/CMakeLists.txt, bindings/python/tests/test_utils.py, bindings/python/utils.py, python/setup.py, requirements.txt, src/utils/LICENSES.txt, storages/python/python-storage-plugins/README.md, storages/python/python-storage-plugins/bson.py, storages/python/tests/CMakeLists.txt, storages/python/tests/test_bson_storage.c
Add BSON plugin for DLite
DLite seems to currently mess up binary strings, by replacing '\\' with '\\\\', which messes up control sequences (e.g. '\n' (hex '0a') becomes '\\\\n', which is interpreted as '\\\\' and 'n' (i.e hex '5c6e')). The plugin is therefore written as a workaround. If this issue can be resolved, the plugin Python code can probably be simplified.
The plugin has only been tested for BSON files generated by itself (by pymongo), not for BSON files generated by other sources.
EDIT: The problem mentioned above has been fixed, so the plugin has been simplified.
=> Bson plugin

bindings/python/tests/CMakeLists.txt, bindings/python/tests/test_property_mappings.py, bindings/python/tests/test_python_bindings.py
Can be used to skip tests that depends on a module that is not available
=> Added support for skipping python tests if they exit with return code 44

bindings/python/CMakeLists.txt, bindings/python/dlite-python.i, bindings/python/tests/test_python_storage.py, src/pyembed/CMakeLists.txt, src/pyembed/dlite-pyembed.c, src/pyembed/dlite-pyembed.h, src/pyembed/dlite-python-mapping.c, src/pyembed/dlite-python-mapping.h, src/pyembed/dlite-python-singletons.c, src/pyembed/dlite-python-singletons.h, src/pyembed/dlite-python-storage.c, src/pyembed/dlite-python-storage.h, src/tests/python/test_pyembed.c
Some suggestion for changes in PR #203 
* Catch ImportError instead of calling pkgutil to determine what modules we have.
pkgutil imports all packages on the system and can be **very** slow.
It may also cause the test to fail due to unrelated problems, e.g. if you have an unrelated buggy package installed on the system.
* Make sure that the DLiteBaseStorage and DLiteBaseMapping made available in the `dlite` scope are exactly the same objects as those we are using at C level.
=> Suggested update for PR #203

examples/dehydrogenation/3-property-mappings/mappings_from_ontology/map_molecules.py, examples/dehydrogenation/3-property-mappings/mappings_from_ontology/map_substance.py, examples/dehydrogenation/README.md, examples/dehydrogenation/ontology/mapsTo.ttl, examples/dehydrogenation/ontology/ontology.py
Changed mapsTo from rdf:Property to owl:AnnotationProperty.
Protege and Owlready2 (and therefore also EMMOntoPy) are based on owl as
base ontology and they change the ontology when loading the original
mapsTo. This is not very practical. We therefore changed the ontology
instead of updating EMMOntoPy. This might be changed in the future.
Commented in the README.md.
Note that we have also made mapsTo an rdfs:subPropertyOf rdfs:SubClassOf. This adds semantic meaning, but is not used for anything right now.
=> Make workflow3 run in dehydrogenation example.

bindings/python/CMakeLists.txt, bindings/python/datamodel.py, bindings/python/dlite-collection-python.i, bindings/python/dlite-collection.i, bindings/python/dlite-entity-python.i, bindings/python/dlite-entity.i, bindings/python/dlite-storage-python.i, bindings/python/dlite-storage.i, bindings/python/tests/CMakeLists.txt, bindings/python/tests/test_datamodel.py, bindings/python/tests/test_python_storage.py, bindings/python/tests/test_utils.py, bindings/python/utils.py, examples/dehydrogenation/1-simple-workflow/calculate_reaction.py, examples/dehydrogenation/1-simple-workflow/molecular_energies.py, examples/dehydrogenation/2-instance-mappings/calculate_reactions.py, examples/dehydrogenation/3-property-mappings/mappings_from_ontology/run_w_onto.py, examples/dehydrogenation/3-property-mappings/mappings_hard_coded/run.py, examples/dehydrogenation/README.md, examples/dehydrogenation/main.py, examples/dehydrogenation/python-mapping-plugins/molecule2substance.py
Keyword arguments cannot be combined with function overloading, hence all function overloading have been removed. This leads to some incompatibilities compared to earlier versions. 
This PR follows up on #202 
All changes in the API are summarised below:
dlite.Instance(...)  # Updated prototype (PR #202). Use the dedicated constructors below:
dlite.Instance.create_from_metaid(metaid, dims, id=None)  # new (PR #202)
dlite.Instance.create_from_url(url, metaid=None)  # new (PR #202)
dlite.Instance.create_from_storage(storage, dims, id=None, metaid=None)  # new (PR #202)
dlite.Instance.create_from_location(driver, location, options=None, id=None)  # new (PR #202)
dlite.Instance.create_metadata(uri, dimensions, properties, description)  # new (PR #202)
dlite.Instance.get_dimension_size(name) …
=> Cleanup keyword arguments

.github/workflows/cd_release.yml
Fixes #234 
The issue is the use of `sed` in general (meaning, no matter the OS).
This fix enforces the use of a bash shell, which should also work on Windows through Git for Windows.
=> Fix deploying on Windows

.github/workflows/container_builds_weekly.yml
Fixes #232 
Fix forward slashes (`/`) in the filename for the cached sha.txt file.
Also, fix the usage of an unset variable in the last step.
=> Fix weekly image builds

bindings/python/dlite-collection-python.i, bindings/python/tests/test_collection.py
close #223 
It is already an error in the C api (and therefore also from Python without `force`) to add an instance with an existing label.
=> Added option `force` to replace an existing instance in a collection.

bindings/python/CMakeLists.txt, bindings/python/tests/test_triplestore.py, bindings/python/triplestore/__init__.py, bindings/python/triplestore/backends/rdflib.py, bindings/python/triplestore/interface.py, bindings/python/triplestore/triplestore.py
Closes #275 
Further improvements, like those liste below should be separate issues. 
* Add additional backends. Candidates include:
- Stardog
- list of tuples
- owlready2/EMMOntoPy
- DLite triplestore (based on Redland librdf)
- Redland librdf
- Apache Jena Fuseki
- Allegrograph
* Update the query() method to return the SPARQL result in a backend-independent way.
* Allow backends to be provided as plugins.
=> Implemented a triplestore Python sub-package

CMakeLists.txt, README.md, bindings/python/tests/CMakeLists.txt, bindings/python/tests/test_property_mappings.py, bindings/python/tests/test_python_storage.py, bindings/python/tests/test_rdf.py, bindings/python/tests/test_triplestore.py
Allow to compile DLite against Python from a virtual environment.
Added instructions to the main README file.
Skipping tests with missing Python dependencies, like rdflib, pint and psycopg2.
=> Virtual environments

bindings/python/dlite-entity-python.i, storages/python/python-storage-plugins/csv.py
Fix the csv plugin such that dates and other data types that pandas convert to type "object" are treated as strings.
=> Allow the csv plugin to read columns with dates and times

bindings/python/mappings.py, bindings/python/tests/test_triplestore.py, bindings/python/triplestore/triplestore.py
Added options to add_mapsTo() and add_function() to provide a user-defined cost. 
The cost may be a float or a function returning the cost. Note that even if the cost is specified as a function, it is only represented in the knowledgebase as a literal identifier, without a fully ontological description of its arguments using e.g. FnO.
=> Interface for adding mapping cost 

.github/docker/Dockerfile-musllinux.template
Fixes #316 
v65 of `setuptools` removed the `msvccompiler` module under `distutils`, which NumPy depends on to build its wheel.
Setting the `SETUPTOOLS_USE_DISTUTILS` environment variable to `stdlib`, making `setuptools` use the built-in `distutils` instead of the version it bundles.
I tested this locally by building the `musllinux` Docker image and run `cibuildwheel` with this image.
What needs to be done now is to merge this, run the [weekly image workflow](https://github.com/SINTEF/dlite/actions/workflows/container_builds_weekly.yml) to generate a new `musllinux` image, which can be used in the CI jobs.
**Note**: The CI job will _not_ work for this PR at this stage.
I tried to add this environment variable to `pyproject.toml`, but I couldn't find a decent way to add this variable …
=> Set the SETUPTOOLS_USE_DISTUTILS env var for musslinux

bindings/python/dlite-entity-python.i, bindings/python/dlite-entity.i, bindings/python/dlite-python.i, bindings/python/tests/test_entity.py
* Added convinient dimnames() and propnames() functions to Metadata.
* Changed some occurences of `dims` to `shape` in Python interface to properties
* Allow to set property shape
* Made Property.ndims immutable
* Added tests
=> Improved Python interface for dlite properties

doc/CMakeLists.txt, doc/Doxyfile.in, doc/fix_readme.cmake
Closes #358 
- Included markdown files in doc/ subdirectories
- Replace slash (dir separator) with underscore in generated references to markdown files
=> Fixed doxygen warnings

.github/workflows/cd_docs.yml
Use the new Sphinx-powered documentation introduced in #367.
This will generate a GH Pages artifact, which can be used as the documentation to be published instead of a dedicated branch.
=> Update CD - Docs workflow

.github/workflows/static_analysis.yml, src/tests/test_json.c, src/tests/test_storage.c, storages/json/tests/test_json_storage.c, storages/python/tests-c/test_blob_storage.c, storages/python/tests-c/test_bson_storage.c, storages/rdf/tests/test_rdf.c
Closes #372 
cppcheck v2.7.4 works fine, but the version on github has suddenly started to complain about STRINGIFY() being an unknown macro. 
A better solution would be to use a newer version of cppcheck in the github CI, but for now ignoring the lines that triggers cppcheck gets us going...
=> Ignore lines with the STRINGIFY() macro, which cppcheck suddenly started to compain about

src/getuuid.c
C strings must be NUL-terminated.
=> Ensure that UUIDs are NUL-terminated

storages/python/python-storage-plugins/postgresql.py, storages/python/tests-python/test_postgresql_storage_python.py
The changes in test_postgresql_storage_python.py makes 
69 - test_postgresql_storage (Failed)
70 - test_postgresql_storage2 (Failed)
72 - test_postgresql_storage_python (Failed)
fail. The two first with 
Error 1: error calling postgresql.load(): RuntimeError: Fetching ('http://onto-ns.com/meta/0.1/Person',) from PostgreSQL database results in a different meta ID to be returned: http://onto-ns.com/meta/0.1/Person
and the last with
Traceback (most recent call last):
File "/home/jesperf/prosjekter/software/dlite/storages/python/tests-python/test_postgresql_storage_python.py", line 45, in <module>
open_start = lines.index(df + 'open(self, uri, options=None):\n')
ValueError: '    def open(self, uri, options=None):\n' is not in list
The changes in test_postgresql_storage_python.py makes …
=> [DO NOT MERGE] Reverting the changes that breaks the postgresql tests

src/dlite-storage.c
Ensure that we fail gracefully if an iterator over instances in a storage cannot be created.
=> Bugfix: proper failure if storage iterator cannot be created.

examples/mappings/mappingfunc.py
Specify explicitely that we use fno to represent mapping functions in the mappings example.
=> Specify explicitely that we use fno to represent mapping functions

requirements_doc.txt
Addressing issue #474 
Added `nbclient<0.6,>=0.2` to fix `jupyter-cache` error. Changed `Sphinx>=4.5.0,<6` to `<Sphinx>=4.5.0,<5` to fix `pydata-sphinx-theme` and `sphinx-book-theme` errors. This raised an incompatibility with `docutils`, which was fixed by adding `docutils<0.18,>=0.14`. 
No errors in the installation.
=> 474 fix python documentation requirements

bindings/python/triplestore/units.py
Change the usage of `os.mkdir()` to `os.makedirs()`, so that the cache directory for the Pint unit registry can be created in Windows. (In Windows, multiple levels of directories need to be created for the user cache path returned by `appdirs.user_cache_dir()`.) Closes #495.
=> Recursive directory creation for unit registry cache

.github/workflows/ci_tests.yml
Fix failing CI tests by downgrading cmake from 3.26.0 to cmake 3.25.2. This solves the issue of calling `find_package(dlite)` when running example ex4 as a CI test  - see issue #509.
This is only a temporary fix:
- If the issue is due to a bug in CMake 3.26.0, then this fix should be reverted when Ubuntu has updated CMake to a working version.
- If the issue is due to a bug in how we generate `dliteConfig.cmake` from `cmake/dliteConfig.cmake.in`, this fix should be reverted when we have fixed that problem.
=> Updated ci-tests.yml to use cmake 3.25.2

.github/workflows/cd_docs.yml, Dockerfile, python/setup.py, requirements.txt
According to SINTEF/oteapi-optimade#117 and EMMC-ASBL/oteapi-dlite#129, using psycopg2-binary v2.9.5 seems to work fine.
Fixes #527 by pinning psycopg2-binary to v2.9.5.
=> Pin psycopg2-binary to v2.9.5

CMakeLists.txt, src/config.h.in, src/dlite-codegen.c
Added workaround for new version of cmake not defining `<project>_VERSION_PATCH`.
Seems to be a bug in cmake - according to the documentation `<project>_VERSION_PATCH`  should be defined: 
https://cmake.org/cmake/help/latest/command/project.html?highlight=project
=> Workaround for new version of cmake not defining <project>_VERSION_PATCH

src/dlite-json.c, src/dlite-json.h, src/tests/test_json.c
Added one more byte to the allocated buffer than expected, which seems to fix the assertion. Requireing this extra byte is unexpected. It seems to be caused by dlite_json_sprint() reporting one byte too little when called with size=0 for a collection with relations! Please add a new issue about this.
Updated documentation and made the implementation of dlite_json_asprint() little more rigorous.
Added two more tests for dlite_json_sprint().
=> Quickfix for assertion error in dlite_json_asprint()

storages/python/python-storage-plugins/redis.py, storages/python/tests-python/test_redis.py
Description
===========
Added `socket_keepalive` option and enabled it by default - this seems to counteract that the redis client hangs indefinitely.
Type of change
--------------
=> Convince redis to not hang

bindings/python/scripts/dlite-validate, src/dlite-storage-plugins.c, src/pyembed/CMakeLists.txt, src/pyembed/dlite-pyembed-utils.c, src/pyembed/dlite-pyembed-utils.h, src/pyembed/dlite-pyembed.c, src/pyembed/dlite-pyembed.h, src/pyembed/dlite-python-mapping.c, src/pyembed/dlite-python-storage.c, src/tests/python/test_pyembed.c, src/utils/strutils.c, src/utils/strutils.h, src/utils/tests/test_bson.c, src/utils/tests/test_strutils.c, storages/python/python-storage-plugins/yaml.py, storages/python/tests-c/CMakeLists.txt, storages/python/tests-c/test_bson_storage.c, storages/python/tests-c/test_postgresql_storage.c, storages/python/tests-c/test_postgresql_storage2.c, storages/python/tests-c/test_yaml_storage.c, storages/python/tests-python/test_bson_storage_python.py, storages/python/tests-python/test_yaml_storage_python.py
Description
===========
Avoid producing a huge number of irrelevant error messages from plugins depending on an unistalled Python package.
Create a simgle warning (that can be turned off) with information about plugins that does load.
Also make the code smarter such that it does not attempt to load a plugin again if it already has failed.
Little unrelated, this PR also skips tests that depend on Python packages not installed in the current environment.
Type of change
--------------
=> Improved error reporting

examples/storage_plugin/plugins/tempprofile.py
Description
===========
It is not intended to call a plugin from a plugin. Doing it seems to cause errors on some systems. 
The easy solution is simply avoiding it by replacing `dlite.Instance.from_location()` with `dlite.Instance.from_json()`.
Type of change
--------------
=> Avoid calling a plugin from a plugin

examples/CMakeLists.txt, examples/datamodel_as_rdf/README.md, examples/datamodel_as_rdf/dataresource.py, examples/datamodel_as_rdf/main.py, examples/datamodel_as_rdf/pydantic_nested.py
The intention with this PR is to make an example of how we can serialise OTEAPI/Pydantic and DLite data models in a consistent way into RDF. The serialisation make use of the datamodel ontology.
Next step is to move the serialisation engine to a sub-package of tripper to make it independent of DLite. 
=> Example of how to serialise data models to RDF

bindings/python/dlite-entity.i, bindings/python/tests/test_entity.py, bindings/python/tests/test_storage.py
=> Fix segfault when calling Instance.to_bytes() for drivers not supporting memsave

bindings/python/dlite-entity-python.i, bindings/python/dlite-entity.i, bindings/python/dlite-misc-python.i, bindings/python/dlite-misc.i, bindings/python/dlite-python.i, bindings/python/dlite-storage.i, bindings/python/factory.py, bindings/python/mappings.py
Reverting some bad code and formatting that was unfortunately introduced.
=> Code cleanup

bindings/python/tests/test_pydantic.py, bindings/python/utils.py, examples/datamodel_as_rdf/README.md, examples/datamodel_as_rdf/dataresource.py, examples/datamodel_as_rdf/dataresource_pydantic2.py, examples/datamodel_as_rdf/main.py, examples/mappings/mappingfunc.py, requirements.txt
Closes #574 
Added support for Pydantic 2.x. Support for Pydantic 1.x is retained.
Also ensure that the mapping example runs with the very old version of Pint (v0.16) required by AiiDA.
=> Added support for Pydantic 2.x

cmake/patch-activate.sh
Added --package option to patch-activate.sh script. This option is needed by the tools like dlite-getuuid when dlite is installed with pip. The reason for this is that the pip package places libdlite.so in the root of the python package instead of in `$VIRTUAL_ENV/lib/`.
The order of the paths in LD_LIBRARY_PATH ensures that shared libraries installed from source get precedence over shared libraries installed with pip.
=> Added --package option to patch-activate.sh script

.github/workflows/ci_tests.yml
Updated ci_tests to install cmake from pip instead of building from source
Closes #518 
=> Install cmake with pip

bindings/python/dlite-storage-python.i, bindings/python/dlite-storage.i, bindings/python/tests/CMakeLists.txt, bindings/python/tests/test_storage_plugins.py, src/dlite-storage-plugins.h, src/dlite-storage.c, src/utils/plugin.c, storages/python/dlite-plugins-python.c
Fixed segfault in iteration over storage plugin names.
Also changed plugin help to be a class method.
=> Fix iterate over storage plugin names

README.md
Added absolute link to figures in README file such that they show up correctly on PyPI: https://pypi.org/project/DLite-Python/. 
=> Make figures show up correctly in README on PyPI

bindings/python/dlite-misc-python.i, bindings/python/dlite-misc.i, bindings/python/tests/test_misc.py, bindings/python/utils.py, src/dlite-bson.c, src/dlite-errors.c, src/dlite-errors.h, src/dlite-mapping-plugins.c, src/dlite-mapping.c, src/dlite-misc.c, src/dlite-misc.h, src/dlite-storage-plugins.c, src/dlite-storage.c, src/dlite-store.c, src/dlite-type-cast.c, src/dlite-type.c, src/dlite.h, src/pyembed/dlite-pyembed.c, src/pyembed/dlite-pyembed.h, src/pyembed/dlite-python-singletons.c, src/pyembed/dlite-python-singletons.h, src/tests/CMakeLists.txt, src/tests/test_errors.c, storages/python/python-storage-plugins/postgresql.py, storages/python/python-storage-plugins/redis.py, storages/python/tests-python/test_redis.py
Made it easy to silence specific DLite error messages both in C and Python.
Also renamed `DLiteErrors` to `DLiteErrCode` since it is an error code (or rather a type for an error code) and not a list of possible error codes.
Also fixed an unrelated issue when loading an instance from BSON (needed by the redis plugin).  Now metadata lookup also include the BSON document containing the instance.  Furthermore, the metadata is properly initiated. This also fixes an issue in the redis plugin.
This PR relates to issue #328 
=> Made it easy to silence specific DLite error messages both in C and Python

src/dlite-json.c, src/dlite-type.c, src/tests/test_json.c, src/utils/strutils.c, src/utils/strutils.h, src/utils/tests/test_strutils.c
We use the collection as a local knowledge base. Since n3-represented literals contains embedded double-quotes it is essential that serialisation and de-serialisation of collections retain embedded double-quotes.
This PR ensures that embedded double-quotes are escaped in the internal representation of relations, which is used by the built-in json encoder/decoder.
=> Support quoted relations in collection

Dockerfile, doc/conf.py.in, examples/TEM_data/requirements.txt
=> 666 sphinx failure

bindings/python/utils.py
Added new utility function get_referred_instances() that recursively finds all instances that are directly or indirectly referred to by an instance (e.g. a collection or a reference property).
Needed by Musicode demo.
=> Added utility function get_referred_instances()

bindings/python/dlite-entity-python.i, bindings/python/tests/test_entity.py
The `__call__()` method only applies to metadata, so moved it from Instance to Metadata.
Fixes the issue with `TypeError: data instances are not callable` in the Musicode demo.
=> Ensure that only metadata is callable

bindings/python/dlite-collection-python.i, bindings/python/dlite-entity-python.i, bindings/python/dlite-entity.i, bindings/python/tests/test_collection.py, bindings/python/tests/test_entity.py
Ensure that the instance returned by `dlite.Instance.copy()` has the right class.
Also applied the same fix to `dlite.Collection.get()`.
Needed by the Musicode demo.
=> Make dlite.Instance.copy() return the correct type

bindings/python/CMakeLists.txt, bindings/python/dlite-collection-python.i, bindings/python/dlite-entity-python.i, bindings/python/dlite-misc-python.i, bindings/python/dlite-python.i, bindings/python/tests/input/Invalid1.json, bindings/python/tests/input/Invalid2.json, bindings/python/tests/test_entity.py, bindings/python/tests/test_storage.py, bindings/python/tests/test_testutils.py, bindings/python/tests/test_utils.py, bindings/python/testutils.py, requirements_dev.txt
Replaced pytest.raises() with an own implementation. Another benefit is that it silence expected DLite error messages written to stderr.
Also removed some unused imports in swig interface. OrderedDict is not longer needed after Python 3.7, which is the lowest version of Python supported by DLite.
Alse allowed dlite.errctl() hide and show arguments to be boolean (for convenience).
Also added some extra tests to reproduce a segfault (issue #686). 
=> Added test utilities

bindings/python/tests/test_entity.py, src/dlite-entity.c
#closes #686
I comment on the fix here to avoid clutter the code with too many comments.
**Short motivation for the change in dlite-entity.c**:
-  `memptr` points to the start of the memory segment of the array data
-  if `memptr` is NULL, the array has not been allocated and there is nothing to free (trying to free it will cause segfault)
- the if statement on line 583 ensures that dlite_type_clear() is only called when there is something to free
The reason that a misspelled shape name results in `memptr` being NULL is that `_instance_propdims_eval()` (dlite-entity.c:455) will fail. This will jump directly to line 495 where the refcount of the instance we are trying to create will be decerased. Since this refcount is already zero, `dlite_instance_free()` will be called with a partly …
=> Fixed segfault caused by misspelled shape

bindings/python/scripts/CMakeLists.txt
Fix typo in CMakeLists.txt when installing dlite-validate
=> Fix typo in CMakeLists.txt when installing dlite-validate

src/triplestore-redland.c
Do not free the librdf world if called from atexit handler.
This may avoid a segfault due to inconsistent state during termination. It is not possible to add a test for this because it depends on the order that the operating system is freeing resources.
=> Do not free the librdf world if called from atexit handler.

bindings/python/tests/input/Invalid3.json, bindings/python/tests/test_entity.py, src/utils/jsmnx.c
=> Changed assertment for invalid json to error

.github/docker/.gitignore, .gitignore, python/.gitignore
=> Updated gitignore files

CMakeLists.txt
Simplified building DLite by updating CMake to automatically detect if DLite is build within a virtual Python environment.
In that case, set the following configurations (if they are not already provided on the command line):
CMAKE_INSTALL_PREFIX
Python3_FIND_VIRTUALENV
PYTHON_VERSION
**Installation with virtualenvwrapper**:
mkvirtualenv newenv
mkdir build-newenv
cd build-newenv
cmake ..
make -j4 install
deactivate
workon newenv
ctest -j4 -E static-code-analysis
**Installation with standard Python virtualenv**:
python -m venv ~/.envs/newenv
mkdir build-newenv
cd build-newenv
cmake ..
make -j4 install
deactivate
. ~/.envs/newenv/activate
ctest -j4 -E static-code-analysis
=> Automatic detect virtualenv

src/dlite-misc.c
Replaced the (mis)use of a session ATEXIT_MARKER_ID state with a local variable to indicate that we are in an atexit handler. The local state is easy to extend.
=> Cleaned up checking whether we are in an atexit handler

cmake/Dockerfile-ubuntu
This PR adds a dockerfile for building with minimal requirements on Ubuntu. All non-skipped tests passes.
The issues in #711 with the tests failing instead of being skipped is not reproduced. This could be due to fixes in DLite applied after the issue was created.
The intention with this PR is simply add the Ubuntu dockerfile such that we have it for testing similar issues in the future. 
Closes #711
=> Added dockerfile for building with Ubuntu and minimal requirements

doc/user_guide/environment_variables.md, src/utils/CMakeLists.txt, src/utils/config.h.in, src/utils/err.c, src/utils/err.h
By default, print DLite errors in color if the error stream is a terminal.
The default can be overridden with the ERR_COLOR environment variable. Like the `--color` option to `ls`, ERR_COLOR can be "always" or "never". All other values correspond to the default.
=> Print DLite errors in color by default

src/dlite-entity.c, storages/python/tests-python/test_image.py
Fixed a few issues when compiling on ubuntu:
- Ensure that the format string of snprintf() is literal (removes a warning)
- Do not test image plugin if scikit-image (skimage) is not installed
=> Improve compiling on Ubuntu

.github/workflows/cd_release.yml
Dependabot PRs #746 and #747 bumped up version of the GitHub download-artifact and upload-artifact actions from v3 to v4. After that releasing to PyPI stopped working.
Trying to revert back to v3 to see if we can get releasing to PyPI working again.
=> Revert github download/upload artifacts actions back to v3

.github/workflows/cd_release.yml, bindings/python/dlite-entity-python.i, bindings/python/dlite-misc-python.i, src/dlite-entity.c, src/dlite-storage-plugins.c, src/dlite-store.c, src/tests/test_getuuid.c, storages/json/dlite-json-storage.c
Corrected syntactic check of id's and uuid's. 
Also rewrote error handling of the return value of  `getuuid()` to correctly handle the new `UUID_EXTRACT` return value. If `getuuid()` can interpret the input UUID, the return value will not be -1 (failure) or 4 (random UUID).
=> Corrected syntactic check of id's and uuid's

requirements_full.txt
Pandas requires now that you have pyarrow installed when reading csv and excel files. See https://pandas.pydata.org/pdeps/0010-required-pyarrow-dependency.html
=> Added pyarrow to requirements_full.txt

.github/workflows/ci_tests.yml, bindings/python/scripts/CMakeLists.txt, bindings/python/scripts/dlite-validate, bindings/python/tests/test_python_storage.py, bindings/python/tests/test_storage.py, bindings/python/utils.py, examples/mappings/requirements.txt, requirements_full.txt, src/dlite-entity.c, storages/python/python-storage-plugins/http.py, storages/python/python-storage-plugins/yaml.py, storages/python/tests-python/input/test_data.ttl, storages/python/tests-python/test_http.py
Added support for fetching instances from http://onto-ns.com/
=> Added support for onto-ns.com

bindings/python/dlite-collection-python.i, bindings/python/mappings.py, examples/read-csv/main.py
Do not raise InsufficientMappingError if a target property is mapped to a concept with not input mappings to when `allow_incomplete=True` or `default` is given.
=> Fix issue in mappings.instantiate_all()

.github/workflows/cd_release.yml
Reverted use of actions/upload-artifact@v4 to v3
This is just a temporary solution since v3 will be deprecated Nov. 30, 2024.
=> Reverted use of actions/upload-artifact@v4 to v3

.github/workflows/cd_release.yml, bindings/python/tests/test_property_mappings.py
Fetch hardcoded namespaces from tripper
=> Update to w3id namespaces

.github/docker/Dockerfile-manylinux.template, .github/docker/Dockerfile-manylinux_x_y.template, .github/docker/Dockerfile-musllinux.template, .github/workflows/cd_release.yml, .github/workflows/ci_build_wheels.yml, .github/workflows/container_builds_weekly.yml, CMakeLists.txt, python/setup.py
Try to make the building of docker images and PyPI wheels leaner by removing all optional requirements. We only want to build and distribute a DLite Python package that only depends on NumPy. The user can always install the additional requirements later, or by install DLite with 
pip install dlite-python[full]
The main feature of this PR is the removal of optional Python requirements when building wheels. Other fixes to make the CI tests to pass, includes:
- Fixed building Windows wheel by explicitly specifying Python version setup.py
- Fixed building musllinux wheel by removing support for Python 3.12 on `musllinux_1_2_i686` (a rare platform) since building NumPy fails by complaining about it can't find NumPy. Can be readded in a later PR
- Document our general support Python 3.12 …
=> WIP: Do not install optional requirements when building docker images for PyPI

.github/workflows/ci_build_wheels.yml, doc/getting_started/installation.md
Add support for building wheels for musllinux_1_2.
Builds on top of PR #860.
=> Add support for musllinux_1_2

.github/docker/Dockerfile-manylinux.template, bindings/python/dlite-entity-python.i, bindings/python/tests/test_utils.py, storages/python/python-storage-plugins/bson.py, storages/python/python-storage-plugins/mongodb.py, storages/python/python-storage-plugins/yaml.py
See comments in issue #811
Infer default values for the `uuid` and `single` options of asdict() to None.
**Note**: This PR changes the behaviour of DLite and may break existing code. 
All tests that are affected by this change have been updated.
=> Infer default values for the `uuid` and `single` options of asdict()

.github/workflows/cd_docs.yml, .github/workflows/ci_tests.yml, python/setup.py
Also changed ubuntu to ubuntu-latest in ci-tests
In the ci_tests workflow, all dependencies are installed (also those of docs). 
The docs dependencies are for a specific version and are not a range of versions,
hence they fail if the required version does not support older python-versions. 
Python3.10 set as standard for this reason.
=> Explicitly set python 3.10 in ci_tests and cd_docs in gitub workflows.

examples/storage_plugin/main.py, python/setup.py, src/dlite-storage-plugins.c, src/pathshash.c, src/pathshash.h, src/pyembed/dlite-python-storage.c
Ensure that Python storages are reloaded if the Python storage plugin path has changed.
=> using plugin in path that is set after instantiation of a data mode fails.

CMakeLists.txt, cmake/valgrind-dlite.supp, cmake/valgrind-python.supp, src/dlite-mapping.c, src/dlite-misc.c, src/pyembed/dlite-python-storage.c, storages/json/dlite-json-storage.c
Fixed memory leaks. The following was done:
- Fixed leak in json_memload()
- Fixed leak in global session when running with DLITE_ATEXIT_FREE set (instead of accepting it, as suggested in PR #888)
- Added a FIXME for a leak in mapping_create_rec() in src/dlite-mappings.c. More work is required. Described in issue #894 
- Ignore external leaks in pydantic and numpy random_bit_generator
- Set DLITE_ATEXIT_FREE when running `make memcheck`. 
=> Fixed memory leaks

CMakeLists.txt, doc/user_guide/transactions.md, src/dlite-datamodel.c, src/dlite-entity.c, src/dlite-json.c, src/dlite-mapping-plugins.c, src/utils/CMakeLists.txt, src/utils/compat.h, src/utils/tests/test_dsl.c, src/utils/tests/test_fileutils.c
Updated cppcheck and corrected some errors that it found.
Background for this PR: After updating cppcheck to 2.13.0, it pointed out a few memory leaks. To make it easier to utilise cppcheck, this PR runs it with cache enabled. After the initial run, this makes cppcheck very fast, making it convenient to use during development.
=> Updated cppcheck and corrected some errors that it found

bindings/python/dlite-entity-python.i, doc/user_guide/environment_variables.md, src/dlite-misc.c
Do not print C errors by default.
Also, avoid calling _dlite.errcheck() as the first thing in Instance.__init__() if SWIG doesn't generate a __new__() method.
=> Do not print C errors by default

doc/contributors_guide/code_changes.md, doc/contributors_guide/index.rst
This is an initial suggestion that should be reviewed.
When agreed, the suggested API should be implemented.
=> Added documentation of how to handle code changes.

bindings/python/dlite-collection-python.i, bindings/python/dlite-entity-python.i, bindings/python/dlite-misc-python.i, bindings/python/dlite-python.i, bindings/python/tests/test_collection.py, src/dlite-errors.c, src/dlite-errors.h, src/dlite-misc.c, src/pyembed/dlite-pyembed.c, src/pyembed/dlite-python-singletons.c, src/tests/test_collection.c, src/tests/test_triplestore.c, src/triplestore.c, storages/rdf/dlite-rdf.c
* Removed duplicated code
* Use switch on enum to ensure that compiler warnings if not all places in the code are updated when a new error code is added.
* Added NameError, PermissionError and InvalidMetadataError.
* Renamed dliteSearchError to dliteLookupError for better correspondance with python.
=> Cleaned up errors and made them more maintainable.

src/dlite-misc.c
…
Fixed logical error/typo. Do not print errors from C to stderr unless DLITE_PYDEBUG is defined.
=> Fixed logical error. Do not print errors from C to stderr unless DLITE_PYDEBUG is defined

src/dlite-json.c
Avoid that dlite segfaults if "dimensions" is null (empty) in JSON and YAML input.
=> Fix segfault if dimensions is null

.github/workflows/container_builds_weekly.yml
The current implementation of the `container_builds_weekly.yml` only publishes the build container if the image on `quay.io/pypa/` has changed, not if we have made any changes in the Dockerfiles that we prepare for building DLite. This means that any changes we do in the Dockerfiles will not be available for the `ci_build_wheels.yml` action.
This PR fixes this broken behaviour, by also including the hash of our local Dockerfile in the file for comparing hashes. 
=> Include the Dockerfile we build in the sha hash for checking whether a new image should be published

bindings/python/dlite-misc-python.i, bindings/python/dlite-misc.i, bindings/python/dlite-python.i, bindings/python/tests/test_collection.py, bindings/python/tests/test_collection_load.py, bindings/python/tests/test_entity.py, bindings/python/tests/test_jstore.py, bindings/python/tests/test_misc.py, src/dlite-misc.c, src/dlite-misc.h, src/utils/tests/test_globmatch.c
Implemented HideDLiteWarnings context manager to make it easy to control what DLite warnings that should be shown.
Also, went through the tests and expected hide warnings in them.
=> Hide warnings

bindings/python/dataset.py, examples/dataset/README.md
Renamed emmo:DataSet to emmo:Dataset
=> Renamed emmo:DataSet to emmo:Dataset

CMakeLists.txt, examples/CMakeLists.txt, examples/minio_storage/main.py, storages/python/tests-python/CMakeLists.txt
The MinIO tests often fails due to the MinIO playground not being available or its storage is filled up by other users.
Instead of failing the whole DLite test suite, it is highly preferable to just mark the MinIO tests as skipped in these cases. 
Tried to implement this PR at the CMake level to avoid unnecessary complicating the `minio_storage` example. However, CMake unfortunately doesn't support combining the TIMEOUT and SKIP_REGULAR_EXPRESSION test properties (as also noted by https://stackoverflow.com/questions/49153984/non-failing-timeout-using-ctest), so timeout was moved to Python.
We currently have not timeout in the `test_minio` cmake test since dlite.Storage doesn't implement timeout. Issue #1067 has been added to address that. 
Also bumped up the CMake requirements to 3.16 …
=> Skip MinIO test when the MinIO playground is not responding or filled up

examples/datamodel_as_rdf/dataresource_pydantic2.py, requirements_full.txt
Updated example models such that they work for pydantic > 2.10.0
=> Updated pydantic examples such that they work for pydantic > 2.10.0

.gitignore, bindings/python/tests/output/.gitignore
Added:
- Typical folder names used for Python Virtual Env's / venv
- CTest created folder is added
- VS Code workspace and moved config folder to a new heading in the file
- Added additional filetype for Python binding test outputs
=> Update .gitignore files

bindings/python/dlite-collection.i, bindings/python/tests/CMakeLists.txt, bindings/python/tests/test_collection_refcount.py, requirements_full.txt
Return a new reference when iterating over a collection and ensure that it is decreased again when the instances goes out of scope (memory managed by dlite).
=> Return a new reference when iterating over a collection.

.github/docker/Dockerfile-manylinux_x_y.template, .github/workflows/cd_release.yml, .github/workflows/ci_build_wheels.yml, .github/workflows/container_builds_weekly.yml
Reverting manylinux wheel from 2_34 to 2_28.
Reason: Building with manylinux_2_34 fails. Also, on https://cibuildwheel.pypa.io/en/stable/options/ they no more refer to manylinux_2_34. manylinux_2_28 will be the new default after manylinux_2014. It is also the highest version that they refer to (except for 2_31, but that is only for ARMv7).
=> Reverting manylinux wheel from 2_34 to 2_28

.github/workflows/cd_release.yml, .github/workflows/ci_build_wheels.yml, doc/user_guide/concepts.md
Update Ubuntu to from 20.04 to 24.04 in the `ci_build_wheels` and `cd_release` workflows.
We use explicit version numbers to avoid surprising changes.
=> Update ubuntu for ci

bindings/python/scripts/CMakeLists.txt, bindings/python/tests/test_entity.py, doc/user_guide/concepts.md, src/dlite-json.c
Allow to omit "dimensions", "properties" and/or "relations" in metadata. They default to be the empty array.
Also updated tests and documentation.
=> Implicit metadata dimensions

.github/workflows/ci_tests.yml, CMakeLists.txt, examples/ex3/main.c, examples/ex5d/example5d.c, src/dlite-entity.c, src/tests/test_collection.c, src/tests/test_dlitebson.c, src/tests/test_json.c, src/triplestore-redland.c, src/utils/compat-src/snprintf.c, src/utils/plugin.c, src/utils/tests/test_bson.c, src/utils/tests/test_snprintf.c, storages/python/README.md, storages/python/dlite-plugins-python.c
Updated to cppcheck 2.18.3 and fixed new memory warnings that it found.
The starting point for this PR is that CI fails at the moment due the installation of cppcheck on Windows is broken (a needed file is not included). See https://github.com/SINTEF/dlite/actions/runs/18153879308/job/52119189099?pr=1217#step:13:321
To address this the following was done:
* On Windows MSVC, disable static-code-analysis (don't know how to fix it) 
* On Windows mingw, install cppcheck with pacman. This brings in version 2.18.3 of cppcheck that reviled a set of new memory warnings
* Fixed the memory warnings
* cppcheck 2.18.3 prints out a lot of information-level output makes it fail. Unfortunately the --disable=information option is not enough to turn off this output. But adding the option …
=> Fix memory warnings reviled by latest cppcheck
