SINTEF/dlite

- storages/python/tests/test_postgresql_storage.c
Fixed segfault in test "test_postgresql_storage" if we cannot connect to the database.
> Fixed segfault in postgresql storage test

- .github/workflows/static_analysis.yml
- CMakeLists.txt
- Dockerfile
- README.md
- examples/ex2/main.c
- examples/ex3/main.c
- examples/ex5d/example5d.c
- src/dlite-datamodel.c
- src/dlite-entity.c
- src/dlite-misc.c
- src/pyembed/dlite-python-mapping.c
- src/tests/test_arrays.c
- src/tests/test_json_entity.c
- src/triplestore.c
- src/utils/compat/snprintf.c
- src/utils/fileutils.c
- src/utils/tests/test_err.c
- src/utils/tgen.c
- storages/hdf5/dh5lite.c
- storages/python/dlite-plugins-python.c
- Fixed issues found by cppcheck.
- Suppressed some false positives using `--inline-suppr` and inline comments in the code
- Added cppcheck to standard ctest test suite
> Fixed issues found by cppcheck and added it to standard test suite

- bindings/python/CMakeLists.txt
- cmake/parse_valgrind_suppressions.awk
- cmake/valgrind-suppressions.txt
- cmake/valgrind_python.py
- src/dlite-entity.c
- src/dlite-storage-plugins.c
- src/pyembed/CMakeLists.txt
- src/pyembed/dlite-pyembed.c
- src/pyembed/tests/test_python_mapping.c
- src/tests/test_datamodel.c
- src/utils/plugin.c
* Greately reduced false positive in "make memcheck" by including host-specific (generated) valgrind suppressions for Python
* Fixed some real memory leaks
> Improved memory leak detection

- bindings/python/CMakeLists.txt
- cmake/parse_valgrind_suppressions.awk
- cmake/valgrind-suppressions.txt
- cmake/valgrind_python.py
- src/dlite-codegen.c
- src/dlite-codegen.h
- src/dlite-entity.c
- src/dlite-storage-plugins.c
- src/pyembed/CMakeLists.txt
- src/pyembed/dlite-pyembed.c
- src/pyembed/tests/test_python_mapping.c
- src/tests/test_datamodel.c
- src/utils/fileutils.c
- src/utils/fileutils.h
- src/utils/plugin.c
- tools/CMakeLists.txt
- tools/dlite-codegen.c
- tools/tests/CMakeLists.txt
Simplified and cleaned up the dlite-codegen tool. Moved some functionality to the dlite library.
> Codegen cleanup

- CMakeLists.txt
Bumped up version number to 0.2.3
> Issue24 consistent naming of instance field names

- .github/workflows/ci.yml
Enables running examples as tests in GitHub CI
> Issue22 run examples in GitHub CI tests

- bindings/python/dlite-entity.i
- bindings/python/dlite-misc-python.i
- bindings/python/dlite-misc.i
- bindings/python/dlite-python.i
- src/dlite-misc.c
- src/dlite-misc.h
- src/pyembed/dlite-pyembed.c
- src/utils/err.c
- src/utils/err.h
- storages/python/dlite-plugins-python.c
- storages/python/python-storage-plugins/postgresql.py
Updated Python bindings and added some extrea docomentation.
> Update python bindings

- CMakeLists.txt
- cmake/valgrind-dlite.supp
- src/dlite-entity.c
- src/dlite-mapping-plugins.c
- src/dlite-mapping-plugins.h
- src/dlite-storage-plugins.c
- src/dlite-storage-plugins.h
- src/pyembed/dlite-pyembed.c
- src/pyembed/dlite-python-storage.c
- src/pyembed/tests/test_python_mapping.c
- src/tests/test_datamodel.c
- src/utils/dsl.h
- src/utils/plugin.c
- src/utils/plugin.h
- storages/json/dlite-json-storage.c
- storages/python/dlite-plugins-python.c
There are still some remaining leaks, but now they are much easier to spot with valgrind.
> Fixed several of memory leaks and updated valgrind suppressions

- bindings/fortran/tests/CMakeLists.txt
- doc/Doxyfile.in
Also removed deprecated doxygen configurations.
> Ensure that we use dlite-codegen from build directory during compilation

- .gitmodules
- src/tests/minunit/MIT-LICENSE.txt
- src/tests/minunit/README.md
- src/tests/minunit/ci/Makefile
- src/tests/minunit/ci/check_example.bat
- src/tests/minunit/ci/check_example.sh
- src/tests/minunit/minunit.h
- src/tests/minunit/minunit_example.c
Minunit is a very simple module with no current development. Hence, there is no need to complicate the maintenance by having it as a git submodule.
> Remove minunit as dlite submubmodule

- src/dlite-codegen.c
- src/dlite-schemas.c
Fixed subtle bug in the memory layout of instances. Also corrected a bug in code generating of metadata.
> Memory bugfix

- bindings/python/dlite-entity-python.i
- src/dlite-misc.c
- src/dlite-type.c
Do not duplicate relations when returning a json representation of a collection.
> Fix python repr

- CMakeLists.txt
- Dockerfile
- Added dependencies
- Removed user permissions from Docker production target
> Fixed syntax for CPack DEB Packages. 

- CMakeLists.txt
- storages/python/CMakeLists.txt
- storages/python/python-storage-plugins/blob.json
- storages/python/python-storage-plugins/blob.py
- storages/python/tests/CMakeLists.txt
- storages/python/tests/test_blob_storage.c
> Common blob metadata

- CMakeLists.txt
- doc/build-with-vs.md
- src/tests/CMakeLists.txt
- src/tests/python/CMakeLists.txt
- storages/json/tests/CMakeLists.txt
- storages/python/tests/CMakeLists.txt
Workaround using PYTHONHOME for embedding the Anaconda interpreter.
> Fix issue151

- bindings/python/dlite-python.i
- bindings/python/tests/test_entity.py
- src/utils/strutils.c
- src/utils/strutils.h
- src/utils/tests/test_sha3.c
- src/utils/tests/test_strutils.c
* Added support for reading any Python object that supports the buffer protocol as blob data.
* Also support reading Python hex-encoded strings as blob data.
> Read blob data from Python

- bindings/python/dlite-entity-python.i
- bindings/python/numpy.i
- bindings/python/tests/test_collection.py
- bindings/python/tests/test_entity.py
- fixed test_entity.py
- fixed test_collection.py
- fixed pickling
- updated numpy.i from latest version of numpy (not nessesary, but seems not to hurt either)
source: https://github.com/numpy/numpy/blob/main/tools/swig/numpy.i
> Fixed the issue that array arguments should not be None

- bindings/python/tests/test_storage.py
- examples/CMakeLists.txt
- examples/dehydrogenation/README.md
- examples/dehydrogenation/main.py
Run the dehydrogenation example as part of the tests
This PR depends on PR #197. Do not merge before #197 has been merged.
> Test dehydrogenation

- .github/workflows/cd_release.yml
- .github/workflows/container_builds_weekly.yml
Fixes #229 
Add missing environment variable.
Test release workflow temporarily (without releasing or pushing to `master`).
*Edit*: This [has been done](https://github.com/SINTEF/dlite/actions/runs/1979319971) and it all seems to be good.
> Fix failing CD for release on PyPI

- .github/workflows/cd_release.yml
> Remove empty folders for publishing distributions

- .github/workflows/cd_release.yml
- .github/workflows/ci_build_wheels.yml
- python/pyproject.toml
Closes #226 
Test the cache in PR.
> Use cache for numpy in testing wheel

- .github/workflows/cd_release.yml
- .github/workflows/ci_build_wheels.yml
> Use hash for `requirements.txt` instead of git SHA

- .github/workflows/cd_release.yml
- .github/workflows/ci_build_wheels.yml
- .github/workflows/ci_tests.yml
- .github/workflows/container_builds_weekly.yml
- .github/workflows/dockerimage.yml
- .github/workflows/static_analysis.yml
Fixes #251 
Note, currently, the release workflow has been changed to test it in this PR - not pushing anything to PyPI or to `master`.
**Edit**: It all seems to be working now (see [this run](https://github.com/SINTEF/dlite/runs/6189937125?check_suite_focus=true), which I cancelled after seeing that most of them succeeded).
> Remove pip cache folder

- bindings/fortran/dlite.f90
- bindings/python/dlite-entity-python.i
- bindings/python/dlite-entity.i
- bindings/python/dlite-python.i
- src/dlite-codegen.c
- src/dlite-entity.c
- src/dlite-entity.h
- src/dlite-json.c
- src/dlite-schemas.c
- src/tests/test_entity.c
- src/tests/test_metamodel.c
- src/tests/test_property.c
- tools/templates/c-header.txt
- tools/templates/c-meta-header.txt
- tools/templates/c-source.txt
- tools/templates/fortran-module.txt
> Remove iri

- src/dlite-entity.c
- src/dlite-entity.h
- src/dlite-type.c
- src/dlite-type.h
- src/tests/test_entity.c
- src/tests/test_type.c
> Implemented calculation of sha3 hash from instance content

- .github/workflows/cd_docs.yml
- README.md
- doc/concepts.md
- added github action for deploying documentation to github pages
- minor fixes in documentation
> Deploy documentation

- .github/workflows/cd_docs.yml
- README.md
Align badges in readme file such that the also look nice in doxygen docs
> Align badges

- bindings/python/CMakeLists.txt
- bindings/python/dlite-entity-python.i
- bindings/python/dlite-entity.i
- bindings/python/dlite-storage-python.i
- bindings/python/rdf.py
- bindings/python/tests/CMakeLists.txt
- bindings/python/tests/rdf.ttl
- bindings/python/tests/test_python_storage.py
- bindings/python/tests/test_rdf.py
- bindings/python/utils.py
- python/setup.py
- requirements.txt
- src/dlite-entity.c
- storages/python/python-storage-plugins/pyrdf.py
- storages/python/python-storage-plugins/yaml.py
- storages/python/tests-python/input/test_data.ttl
- storages/python/tests-python/input/test_data.yaml
- storages/python/tests-python/input/test_meta.ttl
- storages/python/tests-python/input/test_meta.yaml
- storages/python/tests-python/test_yaml_storage_python.py
Added support for serialisation/deserilation in pure python using rdflib. Benefits:
- provide rdf support on systems where redland isn't available (e.g. Windows)
- built-in compatibility with rdflib from Python
> rdflib storage

- bindings/python/dlite-entity-python.i
- bindings/python/dlite-entity.i
- bindings/python/dlite-misc.i
- doc/environment_variables.md
- examples/read-csv/readcsv.py
- src/pyembed/dlite-pyembed.c
- storages/python/dlite-plugins-python.c
- storages/python/python-storage-plugins/yaml.py
- added support for environment variable DLITE_PYDEBUG
- fixed issue #165 (by reimplementing useful fixes from PR #259)
> Improved error reporting from Python plugins

- .github/workflows/cd_docs.yml
- README.md
Makes the doxygen-generated documentation looks nicer
> Allow whitespace in badges

- bindings/python/dlite-collection-python.i
- bindings/python/dlite-storage.i
- bindings/python/tests/test_collection.py
> Cleaned up Python interface to collections and added more tests.

- storages/python/README.md
- storages/python/tests-c/test_postgresql_storage.c
> Added some documentation about how to start a postgresql server and enable the tests

- bindings/python/triplestore/README.md
- bindings/python/triplestore/__init__.py
- bindings/python/triplestore/triplestore.py
Added README file to the triplestore package.
> Triplestore README file

- README.md
- doc/developers/release_instructions.md
> Release instructions

- requirements.txt
This allows the csv plugin to also read excel files...
> Added openpyxl to requirements.txt

- bindings/python/factory.py
Deleted the duplication of instancefactory.
Closes #322
> Remove duplication of instancefactory

- src/dlite-arrays.c
- src/dlite-codegen.c
- src/dlite-collection.c
- src/dlite-datamodel.c
- src/dlite-entity.c
- src/dlite-errors.h
- src/dlite-json.c
- src/dlite-macros.h
- src/dlite-mapping-plugins.c
- src/dlite-mapping.c
- src/dlite-misc.c
- src/dlite-storage-plugins.c
- src/dlite-storage.c
- src/dlite-store.c
- src/dlite-type-cast.c
- src/dlite-type.c
- src/pyembed/dlite-python-mapping.c
- src/pyembed/dlite-python-storage.c
- src/triplestore-builtin.c
- src/triplestore-redland.c
- storages/hdf5/dh5lite.c
- storages/json/dlite-json-storage.c
- storages/python/dlite-plugins-python.c
- storages/rdf/dlite-rdf.c
- tools/dlite-env.c
Please take a look at the dlite-errors.h and the new FAILCODE macros
> Improved error codes

- README.md
- storages/hdf5/CMakeLists.txt
Closes #356 
Tested with HDF5 1.12
> Added support for HDF5 v1.10+

- src/dlite-entity.c
- src/tests/minunit/minunit.h
> Fixed gcc warnings

- bindings/python/triplestore/test_units.py
- bindings/python/triplestore/units.py
- requirements.txt
In addition to style changes this PR also switch from the triplestore implementation currently shipped with dlite (will soon be completely removed) to Tripper.
> Suggesting some improvements in code style

- .github/workflows/cd_docs.yml
Implements the first part of #419.
> Temporarily disable cancel-in-progess CI docs

- doc/coding_guideline.md
This is an initial stub for a coding guideline. 
I don't think we should spend too much time on this, but it is good to have under the documentation for developments.
> Coding guidelines

- CMakeLists.txt
This reverts commit 8e49852b83658679b8b63e32da731873013bc684.
Revert this commit, returning DLite to v0.3.18.
Afterwards, the GitHub release for v3.19, as well as the tag, should be removed.
> Revert "Release v3.19"

- doc/conf.py.in
- doc/contributors_guide/documentation_contributors.md
- requirements_doc.txt
- src/utils/fileutils.h
Description
===========
Added a button to toggle on or off the prompt and output in Python examples.
Type of change
--------------
> Added a button to toggle on or off the prompt and output in Python examples

- src/dlite-type.c
- src/tests/test_type.c
Description
===========
Added two additional tests for dlite-type.
These tests just rules out possible causes of the assertion bug that Treesa experienced some weeks ago.
Type of change
--------------
> Added two additional tests for dlite-type

- examples/CMakeLists.txt
- examples/entities/Chemistry-0.1.json
- examples/entities/aa6060.json
- examples/entities/aa6082.json
- examples/minio_storage/README.md
- examples/minio_storage/fetch.py
- examples/minio_storage/main.py
- examples/minio_storage/store.py
- storages/python/python-storage-plugins/minio.py
- storages/python/tests-python/CMakeLists.txt
- storages/python/tests-python/test_minio.py
Description
===========
Implemented new storage plugin for MinIO.
Type of change
--------------
> MinIO plugin

- CMakeLists.txt
- bindings/python/dlite-entity.i
- bindings/python/dlite-python.i
- bindings/python/tests/test_mapping.py
- cmake/valgrind-python.supp
- src/dlite-entity.c
- src/dlite-entity.h
- src/dlite-json.c
- src/dlite-type.c
- src/pyembed/dlite-python-mapping.c
- src/utils/jsmn.h
- src/utils/jsmnx.c
- storages/python/tests-c/test_bson_storage.c
Description
===========
Removed some memory bugs
Type of change
--------------
> Fixed memory bugs

- bindings/python/CMakeLists.txt
- bindings/python/datamodel.py
- bindings/python/mappings.py
- bindings/python/utils.py
Description
===========
Changed deprecated `dims` variable names to `shape` (in properties) or `dimensions` (creating new instance).
Type of change
--------------
> Replaced some occurrences of `dims`

- doc/getting_started/build/build_against_python_env.md
Description
===========
Updated documentation of how to run cmake with virtual environment.
Type of change
--------------
> cmake with virtualenv

- storages/python/python-storage-plugins/redis.py
Description
===========
Type of change
--------------
> Fixed some typos in the redis plugin

- bindings/python/dlite-collection-python.i
Description
===========
Improved error message from Collection.get_instances()
Type of change
--------------
> Improved error message from Collection.get_instances()

- storages/python/python-storage-plugins/template.py
- storages/python/tests-python/CMakeLists.txt
- storages/python/tests-python/input/template-format.txt
- storages/python/tests-python/input/template-jinja.txt
- storages/python/tests-python/test_template-jinja.py
- storages/python/tests-python/test_template.py
Description
===========
A new simple template-based plugin for generating files. It is related to the code generator, but is intended to generate files based on data instances rather than sources code base on an entity.
Type of change
--------------
> New template-based plugin for generating files

- examples/storage_plugin/README.md
- storages/python/python-storage-plugins/pyrdf.py
- storages/python/python-storage-plugins/yaml.py
Removed non-confirming optional arguments added to plugin methods in the yaml and pyrdf python plugins.
Also added come cosmetic cleanup.
> Cleanup plugins

- examples/storage_plugin/README.md
Description
===========
Closes #570
Type of change
--------------
> Updated README file in storage plugin example.

- bindings/python/dlite-python.i
- bindings/python/tests/test_entity.py
- src/dlite-errors.c
- src/dlite-misc.c
- src/pyembed/dlite-pyembed.c
- src/pyembed/dlite-pyembed.h
- src/pyembed/dlite-python-singletons.c
- src/utils/err.c
- src/utils/err.h
- storages/python/dlite-plugins-python.c
- storages/python/python-storage-plugins/blob.json
- storages/python/python-storage-plugins/yaml.py
Improves changes in PR #584 when addressing issue #580. 
Error messages from within Python plugins are now properly showed. The error type is also shown.
> 580 error messages from python plugins

- bindings/python/dlite-collection-python.i
- bindings/python/dlite-entity-python.i
- bindings/python/dlite-entity.i
- bindings/python/dlite-python.i
- bindings/python/dlite.i
- src/dlite-errors.c
- src/dlite-errors.h
- src/dlite-type.c
- src/pyembed/dlite-python-singletons.c
- src/pyembed/dlite-python-singletons.h
- src/tests/python/plugin1.py
Create and raise Python exceptions corresponding to the dlite error codes.
Individual DLite errors can now be catched from Python based on their type.
> Python errors

- .github/pull_request_template.md
- src/pyembed/dlite-python-singletons.c
> Fix gcc warning

- bindings/python/tests/test_storage.py
- storages/python/python-storage-plugins/yaml.py
Cleaned up docstrings in the YAML storage plugin
> Cleaned up docstrings in the YAML storage plugin

- doc/getting_started/tutorial.md
- storages/python/python-storage-plugins/blob.json
Updated formatting of entities in the tutorial to use the SOFT7 format. Also updated the Blob entity.
> Updated formatting of entities

- bindings/python/dlite-entity-python.i
- bindings/python/utils.py
- requirements.txt
- storages/python/python-storage-plugins/http.py
- storages/python/tests-python/CMakeLists.txt
- storages/python/tests-python/test_http.py
Added a test for the http plugin (issue #569).
Also cleaned up the plugin and improved documentation.
> Test http plugin

- python/setup.py
- requirements_full.txt
Avoid segfault by removing psycopg2-binary from requirement_full.txt
> Removed psycopg2-binary from requirement_full.txt

- bindings/python/mappings.py
- src/dlite-collection.c
Improved handling of special cases in mappings and dlite_collection_find().
> Improved handling of special cases

- .github/docker/Dockerfile-manylinux.template
- .github/docker/Dockerfile-musllinux.template
Build dlite docker containers for python 3.12
> Build dlite docker containers for python 3.12

- examples/TEM_data/main.py
- requirements_dev.txt
- requirements_full.txt
Added more dependency checks before running TEM demo as a test. 
Extra requirements needed by the TEM demo have been added to requirements_full.txt.
> Avoid running TEM demo as a test if dependencies are not fulfilled

- python/setup.py
> Removed dependency on oldest-supported-numpy

- doc/user_guide/environment_variables.md
- src/dlite-misc.c
- src/utils/err.c
- src/utils/err.h
If the ERR_COLOR environment environment variable is defined, write error messages to stderr and stdout in colours.
> Colourful errors

- python/setup.py
> Updated setup.py to read requirements from requirements.txt

- src/utils/session.c
- src/utils/tests/test_session.c
Avoid adding new states to session while freeing all states.
> Avoid adding new states to session while freeing all states.

- CMakeLists.txt
- cmake/SetDefaults.cmake
Updated setting default CMAKE_INSTALL_PREFIX such that it is only set once.
Hopefully this will work on all systems.
> Updated setting default CMAKE_INSTALL_PREFIX such that it is only set once

- storages/python/python-storage-plugins/README.md
- storages/python/tests-python/output/.gitignore
Updated README file for python storage plugins.
Closes #690 
> Updated README file for python storage plugins

- CMakeLists.txt
- bindings/python/scripts/.gitignore
- cmake/uninstall.cmake.in
Also include files installed by setup.py when uninstalling.
Closes #714
> Fix "make uninstall"

- CMakeLists.txt
- bindings/python/dlite-python.i
- src/dlite-bson.c
- src/dlite-entity.c
- src/dlite-misc.c
- src/tests/minunit/minunit.h
- src/utils/CMakeLists.txt
- src/utils/config.h.in
- src/utils/rng.c
- src/utils/rng.h
- src/utils/tests/CMakeLists.txt
- src/utils/tests/test_rng.c
- src/utils/uuid4.c
Used it for generation of UUIDs and snapshot IDs.
> Added high-quality random number generators

- .github/workflows/cd_docs.yml
- .github/workflows/ci_tests.yml
- src/utils/err.c
- src/utils/err.h
* Improved error handling logics
> Avoid duplication of error messages

- src/dlite-entity.h
- src/dlite-misc.h
- src/getuuid.h
- src/utils/strtob.h
- src/utils/unicode.h
> Fixed some doxygen formatting

- .github/workflows/ci_automerge_dependabot.yml
- .github/workflows/ci_cd_updated_master.yml
- .github/workflows/ci_dependabot.yml
- requirements_doc.txt
Automatically created PR from [`ci/dependabot-updates`](https://github.com/SINTEF/dlite/tree/ci/dependabot-updates).
The PR is based on the ['CI - Update dependencies PR' workflow](https://SINTEF.github.io/ci-cd/latest/workflows/ci_update_dependencies/) in [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd).
> [Auto-generated] Update dependencies

- bindings/python/mappings.py
- bindings/python/tests/test_property_mappings.py
Allow to assign default values from existing instance in property mappings. 
> Added default argument to property mappings.

- examples/mappings/mappingfunc.py
Use EMMO instead of FNO in mapping example.
> Use EMMO instead of FNO in mapping example

- .github/docker/Dockerfile-manylinux.template
- .github/docker/Dockerfile-musllinux.template
Remove pyarrow for requirements on weekly build for musllinux and old versions of manylinux since it fails to build on these versions.
> Fix weekly build

- bindings/python/tests/test_python_bindings.py
Running test_python_bindings.py when building wheels fails randomly on Windows.
Tried to simplify stdout redirections. Hopefully that will work better on Windows.
> Simplified test_python_bindings.py

- .github/workflows/cd_docs.yml
Avoid that all deployment of documentation to GH pages gets cancelled.
> Avoid that all deployment of documentation to GH pages gets cancelled.

- storages/python/tests-python/input/test_meta.json
Updated some test entities to new format
> Updated some test entities to new format

- .github/workflows/cd_release.yml
- .github/workflows/ci_build_wheels.yml
- python/pyproject.toml
> Artifacts where not unique, try again.

- .github/workflows/cd_release.yml
> Copy wheels from correct folder

- .github/workflows/cd_release.yml
> Move sdist files correctly

- .github/workflows/cd_release.yml
> Moved all wheels to dist folder and delete original folder

- .github/workflows/cd_release.yml
> Accidentally removed dist folder just before push to pypi

- examples/TEM_data/data/resources.yaml
- examples/TEM_data/demo.py
- examples/TEM_data/tests/test_pipeline.py
Updated TEM demo to use access EMMO with w3id URLs.
> Updating tem demo

- examples/TEM_data/tests/test_coll.py
- storages/python/python-storage-plugins/csv.py
Fixed TEM demo after changing the behaviour of the asdict() method.
> Fixed TEM demo after changing the behaviour of the asdict() method.

- .github/workflows/cd_release.yml
Updated cd_release.yml for publishing to PyPI using OIDC
> Updated cd_release.yml for publishing to PyPI using OIDC

- .github/workflows/cd_release.yml
Remove name form cd_release.yml
> Remove name form cd_release.yml

- .github/workflows/cd_release.yml
Added permissions id-token for write to pypi workflow
> Cd release fix

- doc/user_guide/concepts.md
An attempt to improved the documentation of instances and data models. 
> Update the documentation

- bindings/python/tests/test_dataset1_save.py
- bindings/python/tests/test_dataset2_load.py
Require rdflib for test_dataset*.py
> Require rdflib for test_dataset*.py

- src/utils/tests/test_uri_encode.c
> Added two more tests

- requirements_full.txt
Since the req was too loose it is now failing in master.
This is a fix so that it works in master, and then investigation of why it fails with newer pydnatic shall happen in a dedicated PR
> Pydantic 2.9.2 works, but not 2.10.1.

- bindings/python/scripts/CMakeLists.txt
Added tests for dlite-validate of instances with ref-types.
Merge PR #1010 first to get rid of the segfaults.
> Added tests for dlite-validate of instances with ref-types

- .github/workflows/container_builds_weekly.yml
Assign environment variables the GitHub when building weekly containers.
> Assign environment variables the GitHub when building weekly containers

- CMakeLists.txt
- python/setup.py
- src/utils/integers.h.in
Update setup.py on top of branch build-wheel4
> WIP: Update setup.py on top of branch build-wheel4

- .github/workflows/ci_tests.yml
- bindings/python/CMakeLists.txt
- bindings/python/dlite-python.i
- examples/CMakeLists.txt
- requirements_full.txt
- src/dlite-errors.c
- src/dlite-errors.h
- src/pyembed/dlite-pyembed.c
- storages/python/python-storage-plugins/minio.py
- storages/python/tests-c/test_postgresql_storage.c
- storages/python/tests-python/CMakeLists.txt
- storages/python/tests-python/test_minio.py
Added timeout option to MinIO storage plugin. Although not implemented as described in issue #1067, this PR address the intension or that issue.
Closes #1067
> Added timeout option to MinIO storage plugin

- requirements_dev.txt
- requirements_doc.txt
- requirements_full.txt
Downgrade sphinx to avoid dependency conflicts
> Downgrade sphinx to avoid dependency conflicts

- CMakeLists.txt
Corrected version number to 0.5.27 (was not set correctly by the CI system)
> Corrected version number to 0.5.27

- .github/workflows/cd_release.yml
- python/pyproject.toml
- requirements.txt
- requirements_dev.txt
> Fixed so that version requirements are in agreement also in python

- README.md
> Added PINK to acknowledgement

- bindings/python/dlite-misc.i
- bindings/python/dlite-python.i
- bindings/python/dlite-type.i
- bindings/python/tests/test_storage.py
- doc/user_guide/datamodels.md
- examples/storage_plugin/main.py
- src/dlite-misc.c
- src/dlite-misc.h
- src/dlite-type.c
- src/tests/test_type.c
- src/utils/err.c
- src/utils/err.h
- src/utils/tests/test_err.c
- storages/python/python-storage-plugins/yaml.py
- storages/rdf/dlite-rdf.c
Improved support for error levels and added dlite_info() and dlite_debug().
Also did some general cleanup and bug fixes.
> Improved support for error levels

- README.md
> Move the banner to the top of the README file

- LICENSE
Update license copyright years
> Update license copyright years
